title: Umbraco CMS Foundations
description: Learn about the different sections found in the Umbraco CMS backoffice and how to use the core features and functionality to manage your content.
theme: just-the-docs

plugins:
  - jekyll-default-layout

url: https://bkclerke.github.io/Diagram.UmbracoGuides


aux_links:
  Template Repository: https://github.com/bkclerke/Diagram.UmbracoGuides
